Feature search users
vkaidalov/chat-with-anyone pull request #13
Opened 2019-08-27 16:51 UTC by AndsoiIo

2019-08-28 17:58 UTC, vkaidalov requested changes
исправь отступы в строках 392-396 и добавь новую строку в конце файла

2019-08-28 18:01 UTC, hesoyam11 commented
помести класс UserList перед UserDetail, так будет логичнее

2019-08-28 18:05 UTC, hesoyam11 commented
сделай отступы вот так, а тот PEP 8 в PyCharm ругается:
`parameters=[
    {
        'in': 'header',
        'name': 'Authorization',
        'schema': {'type': 'string'},
        'required': 'true'
    }, 
    {
        'in': 'query',
        'name': 'username',
        'schema': {'type': 'string'},
    }
]`

2019-08-28 18:19 UTC, hesoyam11 commented
сервер щас упадет, если передать в page или page_size строки, которые не числа. а это можно сделать, если, например, стучаться к серверу через постман, а не сваггер юай. + следует ограничить клиентам максимальное значение page_size, например, 50 штук, чтобы не было возможности дудосить.

2019-08-28 18:20 UTC, hesoyam11 commented
еще надо запулить девелоп, потому что щас у тебя сайн ин не пропускает - в новой версии девелопа пароли захэшированы, поэтому нужно будет пересоздать пользователей в БД.

2019-08-28 18:31 UTC, hesoyam11 commented on api_server/chat_with_anyone/routes.py
> -from .views.users import UserDetail, ContactDetail, ContactList
это тест!

2019-08-28 18:32 UTC, AndsoiIo commented on api_server/chat_with_anyone/routes.py
> -from .views.users import UserDetail, ContactDetail, ContactList
тест успешен?)

2019-08-28 18:35 UTC, hesoyam11 commented on api_server/chat_with_anyone/routes.py
> -from .views.users import UserDetail, ContactDetail, ContactList
> тест успешен?)

та норм

2019-08-28 19:43 UTC, AndsoiIo commented
> исправь отступы в строках 392-396 и добавь новую строку в конце файла

а что не так с отступами в тех строках?

2019-08-30 20:11 UTC, vkaidalov submitted a review, later dismissed

2019-08-31 13:19 UTC, dziubakseniia approved these changes
Отлично)

2019-08-31 13:19 UTC, merged