Feature chat messages
vkaidalov/chat-with-anyone pull request #31
Opened 2019-09-11 07:25 UTC by tukva

2019-09-11 15:44 UTC, AndsoiIo commented
Влад, закомменти пожалуйста все тесты в файле тестов, чтобы тревис не выдавал ошибок. Тесты устарели и их нужно переписать.
Можешь даже сразу покрыть тестами свой кусок кода, что ты отправил в пул реквесте.

2019-09-15 16:03 UTC, hesoyam11 commented on api_server/chat_with_anyone/routes.py
> +        web.view(r'/api/users/{user_id:\d+}/user_chats/', UserChats),
может лучше просто `chats` вместо `user_chats`?

2019-09-15 16:08 UTC, AndsoiIo commented on api_server/chat_with_anyone/routes.py
> +        web.view(r'/api/users/{user_id:\d+}/user_chats/', UserChats),
+

2019-09-17 10:18 UTC, dziubakseniia commented on api_server/chat_with_anyone/routes.py
> +        web.view(r'/api/users/{user_id:\d+}/user_chats/', UserChats),
Аналогично

2019-09-17 19:42 UTC, dziubakseniia commented on api_server/chat_with_anyone/tests/test_chats.py
>  async def test_get_list_chats(cli):
Стоить закоментить всё, что касается методов тестов. Иначе, получается, async ожидает, что его вызовут, то в итоге там ничего не происходит.

2019-09-17 20:06 UTC, dziubakseniia commented on api_server/chat_with_anyone/views/chats.py
> +        if user.id != user_message.user_id:
А зачем тут проверка, если мы в не указываем user_id в самом endpoint?)

2019-09-17 20:09 UTC, dziubakseniia commented on api_server/chat_with_anyone/views/chats.py
> +        if user.id != user_message.user_id:
Тут то же самое с user.id

2019-09-17 20:11 UTC, dziubakseniia commented on api_server/chat_with_anyone/views/users.py
> +    last_message_at = fields.DateTime(required=True
Тут или последнюю скобочку вверх перенеси, или required=True на отдельную строчку.

2019-09-17 20:17 UTC, dziubakseniia requested changes
Комменты непосредственно к строкам)

2019-09-18 10:46 UTC, dziubakseniia approved these changes

2019-09-18 10:46 UTC, dziubakseniia commented on api_server/chat_with_anyone/views/chats.py
> +                {'message': "Changing another user's message is prohibited"},
Тут надо на удаление поменять.

2019-09-18 10:46 UTC, merged